services:
  app:
    build:
       dockerfile: Dockerfile.nvidia
       target: app
    ports:
       - 8000:7860
    env_file:
       - .env
    volumes:
       - ./yologp:/app/yologp
       - ./assets:/app/assets
       - ./data:/app/data
    deploy:
       resources:
         reservations:
           devices:
             - driver: nvidia
               count: 1
               capabilities: [ gpu ]
  # hf_app:
  #   build:
  #     dockerfile: Dockerfile.hf
  #     target: app
  #   ports:
  #     - 8000:7860
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./inference_gradio_app.py:/app/inference_gradio_app.py
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [ gpu ]
